apiVersion: apps/v1
kind: Deployment
metadata:
  name: zain-backend
  labels:
    app: zain-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: zain-backend
  template:
    metadata:
      labels:
        app: zain-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "{{ .Values.env.DB_HOST }}"
            - name: DB_PORT
              value: "{{ .Values.env.DB_PORT }}"
            - name: DB_USER
              value: "{{ .Values.env.DB_USER }}"
            - name: DB_PASSWORD
              value: "{{ .Values.env.DB_PASSWORD }}"
            - name: DB_NAME
              value: "{{ .Values.env.DB_NAME }}"
            - name: JWT_SECRET
              value: "{{ .Values.env.JWT_SECRET }}"
