apiVersion: v1
kind: Service
metadata:
  name: zain-backend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: zain-backend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
