replicaCount: 1

image:
  repository: eslamzain99/zain-hotel-backend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

env:
  DB_HOST: database
  DB_PORT: "5432"
  DB_USER: zain
  DB_PASSWORD: zain123
  DB_NAME: hotel_db
