apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zain-backend
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/eslam-devops/Zain-Luxury-Hotel.git
    targetRevision: main
    path: helm/backend
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: zain-hotel

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
